In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Adding macroeconomic data from Bloomberg

In [3]:
df_macrodata = pd.read_excel('raw_data/Macroeconomic data.xlsx', sheet_name='Macroeconomic Values', index_col=0)
df_macrodata

Mid Price Fed  Tayler Rule Estimate  Job Quality Index (JQI)  \
Date                                                                       
2020-12-31           0.36             -0.019950                81.622508   
2019-12-31           2.16              4.866175                79.731742   
2018-12-31           1.83              5.097942                82.151842   
2017-12-31           1.00              4.129083                83.233492   
2016-12-31           0.39              3.564383                83.019850   
2015-12-31           0.13              2.589708                82.796267   
2014-12-31           0.09              2.198917                81.495700   
2013-12-31           0.11              0.931408                80.060792   
2012-12-31           0.14              0.771100                79.811558   

            Consumer Price Index (yoy %)  Unemployment Rate  \
Date                                                          
2020-12-31                      1.233333           8.108333   
2019-12-31                      1.816667           3.683333   
2018-12-31                      2.450000           3.891667   
2017-12-31                      2.116667           4.350000   
2016-12-31                      1.266667           4.875000   
2015-12-31                      0.125000           5.275000   
2014-12-31                      1.633333           6.158333   
2013-12-31                      1.483333           7.358333   
2012-12-31                      2.083333           8.075000   

            Uncertainty About GDP Growth - Broadly Similar  \
Date                                                         
2020-12-31                                        0.333333   
2019-12-31                                       12.250000   
2018-12-31                                       14.000000   
2017-12-31                                       13.500000   
2016-12-31                                       13.750000   
2015-12-31                                       14.750000   
2014-12-31                                       14.250000   
2013-12-31                                       11.250000   
2012-12-31                                        1.800000   

            Risks to GDP Growth - Broadly Balance  Optimism Index  \
Date                                                                
2020-12-31                               5.666667       99.616667   
2019-12-31                               7.000000      102.991667   
2018-12-31                              12.000000      106.683333   
2017-12-31                              11.500000      104.850000   
2016-12-31                              10.500000       95.291667   
2015-12-31                              12.250000       96.133333   
2014-12-31                              13.500000       95.608333   
2013-12-31                              10.250000       92.425000   
2012-12-31                               6.000000       92.208333   

                      M2  OECD Leading Indicator (12-mo % chg)  \
Date                                                             
2020-12-31  17684.083583                              0.390909   
2019-12-31  14840.074950                              1.066667   
2018-12-31  14120.424967                              3.091667   
2017-12-31  13597.108317                              3.500000   
2016-12-31  12863.791667                              1.566667   
2015-12-31  12046.183350                              1.508333   
2014-12-31  11389.858317                              2.708333   
2013-12-31  10728.133300                              2.783333   
2012-12-31  10051.866700                              1.725000   

            Fed Funds Rate (%)  3-Month T-Bill Rate (%)  \
Date                                                      
2020-12-31            0.536260                 0.348511   
2019-12-31            2.279693                 2.084291   
2018-12-31            1.908046                 1.954138   
2017-12-31      

In [4]:
df_macrodata = df_macrodata.iloc[3:8]

In [5]:
df_macrodata

Mid Price Fed  Tayler Rule Estimate  Job Quality Index (JQI)  \
Date                                                                       
2017-12-31           1.00              4.129083                83.233492   
2016-12-31           0.39              3.564383                83.019850   
2015-12-31           0.13              2.589708                82.796267   
2014-12-31           0.09              2.198917                81.495700   
2013-12-31           0.11              0.931408                80.060792   

            Consumer Price Index (yoy %)  Unemployment Rate  \
Date                                                          
2017-12-31                      2.116667           4.350000   
2016-12-31                      1.266667           4.875000   
2015-12-31                      0.125000           5.275000   
2014-12-31                      1.633333           6.158333   
2013-12-31                      1.483333           7.358333   

            Uncertainty About GDP Growth - Broadly Similar  \
Date                                                         
2017-12-31                                           13.50   
2016-12-31                                           13.75   
2015-12-31                                           14.75   
2014-12-31                                           14.25   
2013-12-31                                           11.25   

            Risks to GDP Growth - Broadly Balance  Optimism Index  \
Date                                                                
2017-12-31                                  11.50      104.850000   
2016-12-31                                  10.50       95.291667   
2015-12-31                                  12.25       96.133333   
2014-12-31                                  13.50       95.608333   
2013-12-31                                  10.25       92.425000   

                      M2  OECD Leading Indicator (12-mo % chg)  \
Date                                                             
2017-12-31  13597.108317                              3.500000   
2016-12-31  12863.791667                              1.566667   
2015-12-31  12046.183350                              1.508333   
2014-12-31  11389.858317                              2.708333   
2013-12-31  10728.133300                              2.783333   

            Fed Funds Rate (%)  3-Month T-Bill Rate (%)  \
Date                                                      
2017-12-31            1.100000                 0.933962   
2016-12-31            0.512452                 0.306437   
2015-12-31            0.261494                 0.041801   
2014-12-31            0.250000                 0.024981   
2013-12-31            0.250000                 0.051000   

            10-Year Treasury Yield (%)  
Date                                    
2017-12-31                    2.326269  
2016-12-31                    1.836897  
2015-12-31                    2.131226  
2014-12-31                    2.529119  
2013-12-31                    2.336846

In [6]:
col = df_macrodata.columns
col

Index(['Mid Price Fed', 'Tayler Rule Estimate', 'Job Quality Index (JQI)',
       'Consumer Price Index (yoy %)', 'Unemployment Rate',
       'Uncertainty About GDP Growth - Broadly Similar',
       'Risks to GDP Growth - Broadly Balance', 'Optimism Index', 'M2',
       'OECD Leading Indicator (12-mo % chg)', 'Fed Funds Rate (%)',
       '3-Month T-Bill Rate (%)', '10-Year Treasury Yield (%)'],
      dtype='object')

In [7]:
#Go trough whole process again

In [8]:
df2014 = pd.read_csv('raw_data/2014_Financial_Data.csv')
df2015 = pd.read_csv('raw_data/2015_Financial_Data.csv')
df2016 = pd.read_csv('raw_data/2016_Financial_Data.csv')
df2017 = pd.read_csv('raw_data/2017_Financial_Data.csv')
df2018 = pd.read_csv('raw_data/2018_Financial_Data.csv')

In [9]:
df2014 = df2014.rename({'2015 PRICE VAR [%]':'PRICE_VAR'},axis =1)
df2015 = df2015.rename({'2016 PRICE VAR [%]':'PRICE_VAR'},axis =1)
df2016 = df2016.rename({'2017 PRICE VAR [%]':'PRICE_VAR'},axis =1)
df2017 = df2017.rename({'2018 PRICE VAR [%]':'PRICE_VAR'},axis =1)
df2018 = df2018.rename({'2019 PRICE VAR [%]':'PRICE_VAR'},axis =1)

In [10]:
# Adding the Benchmark for each year
df2014['S&P 500'] = -0.0073
df2015['S&P 500'] = 0.0954
df2016['S&P 500'] = 0.1942
df2017['S&P 500'] = -0.0624
df2018['S&P 500'] = 0.2888

In [11]:
for colname in col:

    df2018[colname] = df_macrodata[colname][0]
    df2017[colname] = df_macrodata[colname][1]
    df2016[colname] = df_macrodata[colname][2]
    df2015[colname] = df_macrodata[colname][3]
    df2014[colname] = df_macrodata[colname][4]

In [12]:
df2018

Unnamed: 0       Revenue  Revenue Growth  Cost of Revenue  Gross Profit  \
0         CMCSA  9.450700e+10          0.1115     0.000000e+00  9.450700e+10   
1           KMI  1.414400e+10          0.0320     7.288000e+09  6.856000e+09   
2          INTC  7.084800e+10          0.1289     2.711100e+10  4.373700e+10   
3            MU  3.039100e+10          0.4955     1.250000e+10  1.789100e+10   
4            GE  1.216150e+11          0.0285     9.546100e+10  2.615400e+10   
...         ...           ...             ...              ...           ...   
4387       YRIV  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
4388       YTEN  5.560000e+05         -0.4110     0.000000e+00  5.560000e+05   
4389       ZKIN  5.488438e+07          0.2210     3.659379e+07  1.829059e+07   
4390        ZOM  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
4391       ZYME  5.301900e+07          0.0243     0.000000e+00  5.301900e+07   

      R&D Expenses  SG&A Expense  Operating Expenses  Operating Income  \
0     0.000000e+00  6.482200e+10        7.549800e+10      1.900900e+10   
1     0.000000e+00  6.010000e+08        3.062000e+09      3.794000e+09   
2     1.354300e+10  6.750000e+09        2.042100e+10      2.331600e+10   
3     2.141000e+09  8.130000e+08        2.897000e+09      1.499400e+10   
4     0.000000e+00  1.811100e+10        4.071100e+10     -1.455700e+10   
...            ...           ...                 ...               ...   
4387  0.000000e+00  3.755251e+06        3.755251e+06     -3.755251e+06   
4388  4.759000e+06  5.071000e+06        9.830000e+06     -9.274000e+06   
4389  1.652633e+06  7.020320e+06        8.672953e+06      9.617636e+06   
4390  1.031715e+07  4.521349e+06        1.664863e+07     -1.664863e+07   
4391  5.668400e+07  2.945700e+07        8.614600e+07     -3.312700e+07   

      Interest Expense  ...  Consumer Price Index (yoy %)  Unemployment Rate  \
0         3.542000e+09  ...                      2.116667               4.35   
1         1.917000e+09  ...                      2.116667               4.35   
2        -1.260000e+08  ...                      2.116667               4.35   
3         3.420000e+08  ...                      2.116667               4.35   
4         5.059000e+09  ...                      2.116667               4.35   
...                ...  ...                           ...                ...   
4387      1.105849e+07  ...                      2.116667               4.35   
4388      0.000000e+00  ...                      2.116667               4.35   
4389      1.239170e+06  ...                      2.116667               4.35   
4390      0.000000e+00  ...                      2.116667               4.35   
4391      1.660000e+05  ...                      2.116667               4.35   

      Uncertainty About GDP Growth - Broadly Similar  \
0                                               13.5   
1                                               13.5   
2                                               13.5   
3                                               13.5   
4                                               13.5   
...                                              ...   
4387                                            13.5   
4388                                            13.5   
4389                                            13.5   
4390                                            13.5   
4391                                            13.5   

      Risks to GDP Growth - Broadly Balance  Optimism Index            M2  \
0                                      11.5          104.85  13597.108317   
1                                      11.5          104.85  13597.108317   
2                                      11.5          104.85  13597.108317   
3                                      11.5          104.85  13597.108317   
4                                      11.5          104.85  13597.108317   
...                                     ...             ...

In [13]:
print(df2014.shape)
print(df2015.shape)
print(df2016.shape)
print(df2017.shape)
print(df2018.shape)

(3808, 239)
(4120, 239)
(4797, 239)
(4960, 239)
(4392, 239)


In [14]:
df = pd.concat([df2014,df2015,df2016,df2017,df2018])
df['PRICE_VAR']=df['PRICE_VAR']/100

In [15]:
#create index
df.index = np.arange(1,22078) 

In [16]:
df = df.drop(['Unnamed: 0'], axis=1)

In [17]:
#Threshhold
Threshhold = 22077*(0.5)
df = df.dropna(thresh=Threshhold, axis=1)
df = df.dropna(thresh=220*0.5-2)

In [18]:
#Creating dummy variables
sector = df['Sector'] 
sector_dummies = pd.get_dummies(sector)
df=df.drop('Sector', axis=1)

In [19]:
#Estimation missing data points
df = df.fillna(value=df.median())

In [20]:
#Removing outliers
df = df[np.abs(df-df.mean()) <= (2.33*df.std())].dropna()
df.shape

(11592, 235)

In [21]:
df = df.join(sector_dummies)

In [22]:
#Adding classification buy/hold/sell

In [23]:
dif = df['PRICE_VAR'] - df['S&P 500']

signal = []

for number in dif:
    if number<-0.025:
        signal.append('Sell')
    elif number<0.025:
        signal.append('Hold')       
    else:
        signal.append('Buy')

In [24]:
df['Signal']= signal

In [25]:
df = df.drop(['S&P 500','Class','PRICE_VAR'], axis=1) 

In [26]:
df.index = np.arange(1,11593) 

## Decision Trees

In [27]:
#Assigning values
X = df.drop('Signal', axis=1)
y = df['Signal']

In [28]:
# Create Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [29]:
#scale our data to avoid issues (X_scaled = X_std * (max - min) + min)
from sklearn.preprocessing import MinMaxScaler

In [30]:
#creating an instance
scaler = MinMaxScaler()

#adjusting scaler only based on the training set (without test values to prevent data leakage)
scaler.fit(X_train)

MinMaxScaler()

In [31]:
#perform the transformation
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
from sklearn.ensemble import RandomForestClassifier

# Create classifier object and fit it to data
forest = RandomForestClassifier(criterion='gini', random_state=0, n_jobs=-1, max_depth=10)
forest.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_jobs=-1, random_state=0)

In [33]:
y_pred = forest.predict(X_test)

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         Buy       0.64      0.39      0.49      1406
        Hold       0.00      0.00      0.00       224
        Sell       0.61      0.87      0.72      1848

    accuracy                           0.62      3478
   macro avg       0.42      0.42      0.40      3478
weighted avg       0.58      0.62      0.58      3478



C:\Users\Christian Rauhut\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
from sklearn import metrics
print('Confusion matrix: \n', 
      metrics.confusion_matrix(y_test, y_pred))

Confusion matrix: 
 [[ 550    0  856]
 [  59    0  165]
 [ 247    0 1601]]


In [36]:
#Cross Validation

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
    train_test_split(X, y, 
                     test_size=0.3, 
                     random_state=0, 
                     stratify=y)

# Import necessary functions
from sklearn.model_selection import StratifiedKFold, cross_val_score

# Create k-Fold CV and LogReg object
kFold = StratifiedKFold(n_splits=5)
forestcv = RandomForestClassifier(criterion='gini', random_state=0, n_jobs=-1)

# Run CV and print results
scores = cross_val_score(forestcv, X_train, y_train, cv=kFold)
print(scores)
print('CV accuracy on train set: {0: .3f} +/- {1: .3f}'.format(np.mean(scores), np.std(scores)))

[0.61614295 0.62784966 0.61737523 0.61429452 0.62330456]
CV accuracy on train set:  0.620 +/-  0.005


In [ ]:
#Gridsearch
from sklearn.model_selection import GridSearchCV

# Max depth
maxDepth = np.array([1, 2, 5, 10])

# Minimum number of samples required to split any internal node 
minSamplesNode = np.array([2, 5, 10])

# The minimum number of samples required to be at a leaf/terminal node
minSamplesLeaf = np.array([10, 20, 30])

# Import necessary functions
from sklearn.model_selection import StratifiedKFold, cross_val_score

# Create k-Fold CV object
kFold = StratifiedKFold(n_splits=10)


# Define the hyperparameter values to be tested
param_grid = {'criterion': ['gini', 'entropy'],
              'max_depth': maxDepth,
              'min_samples_split': minSamplesNode,
              'min_samples_leaf': minSamplesLeaf}

# Run brute-force grid search
gs = GridSearchCV(estimator=RandomForestClassifier(random_state=0),
                  param_grid=param_grid,
                  scoring='accuracy',
                  cv=kFold, n_jobs=-1)
gs = gs.fit(X_train, y_train)
print(gs.best_score_)
print(gs.best_params_)

y_pred = forest.predict(X_test)

print(classification_report(y_test,y_pred))