In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
plt.rcParams['font.size'] = 14
plt.style.use('seaborn-whitegrid')

In [2]:
df = pd.read_csv('cleaned_data/Cleaned Data.csv',index_col=[0])

In [3]:
df

Revenue  Revenue Growth  Cost of Revenue  Gross Profit  \
2      3.734148e+09          1.1737     2.805625e+09  9.285226e+08   
5      1.790960e+10          0.0076     1.153980e+10  6.369800e+09   
15     5.727000e+09          0.0214     3.523600e+09  2.203400e+09   
16     1.972400e+10          0.0083     1.304100e+10  6.683000e+09   
17     8.268000e+09          0.0268     5.297000e+09  2.971000e+09   
...             ...             ...              ...           ...   
22070  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22073  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22075  5.488438e+07          0.2210     3.659379e+07  1.829059e+07   
22076  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22077  5.301900e+07          0.0243     0.000000e+00  5.301900e+07   

       R&D Expenses  SG&A Expense  Operating Expenses  Operating Income  \
2      1.083303e+08  3.441414e+08        7.939267e+08      1.345959e+08   
5      0.000000e+00  3.474300e+09        3.412400e+09      2.957400e+09   
15     0.000000e+00  1.480500e+09        1.598700e+09      6.047000e+08   
16     0.000000e+00  3.709000e+09        4.162000e+09      2.521000e+09   
17     1.220000e+08  1.505000e+09        1.704000e+09      1.267000e+09   
...             ...           ...                 ...               ...   
22070  1.572500e+07  5.269000e+06        2.099400e+07     -2.099400e+07   
22073  0.000000e+00  3.755251e+06        3.755251e+06     -3.755251e+06   
22075  1.652633e+06  7.020320e+06        8.672953e+06      9.617636e+06   
22076  1.031715e+07  4.521349e+06        1.664863e+07     -1.664863e+07   
22077  5.668400e+07  2.945700e+07        8.614600e+07     -3.312700e+07   

       Interest Expense  Earnings before Tax  ...  Consumer Cyclical  \
2          1.214869e+07         1.753823e+08  ...                  0   
5          3.024000e+08         2.707700e+09  ...                  0   
15         6.040000e+07         4.669000e+08  ...                  0   
16         2.840000e+08         2.382000e+09  ...                  0   
17         1.220000e+08         1.240000e+09  ...                  0   
...                 ...                  ...  ...                ...   
22070      0.000000e+00        -2.113800e+07  ...                  0   
22073      1.105849e+07        -1.482451e+07  ...                  0   
22075      1.239170e+06         8.416324e+06  ...                  0   
22076      0.000000e+00        -1.664769e+07  ...                  0   
22077      1.660000e+05        -3.438500e+07  ...                  0   

       Consumer Defensive  Energy  Financial Services  Healthcare  \
2                       1       0                   0           0   
5                       1       0                   0           0   
15                      1       0                   0           0   
16                      1       0                   0           0   
17                      1       0                   0           0   
...                   ...     ...                 ...         ...   
22070                   0       0                   0           1   
22073                   0       0                   0           0   
22075                   0       0                   0           0   
22076                   0       0                   0           0   
22077                   0       0                   0           1   

       Industrials  Real Estate  Technology  Utilities  Signal  
2                0            0           0          0    Sell  
5                0            0           0          0     Buy  
15               0            0           0          0     Buy  
16               0            0           0          0     Buy  
17               0            0           0          0     Buy  
...            ...          ...         ...        ...     ...  
22070            0            0           0          0     Buy  
22073            0            1           0          0  

In [4]:
df['Signal'].value_counts()

Sell    6153
Buy     4681
Hold     745
Name: Signal, dtype: int64

In [5]:
SignalFac = []

for string in df['Signal']:
    if string == 'Sell':
        SignalFac.append(0)
    elif string == 'Hold':
        SignalFac.append(1)    
    else:
        SignalFac.append(2)

In [6]:
df['SignalFac'] = SignalFac
df.drop('Signal', axis=1, inplace=True)

In [7]:
df

Revenue  Revenue Growth  Cost of Revenue  Gross Profit  \
2      3.734148e+09          1.1737     2.805625e+09  9.285226e+08   
5      1.790960e+10          0.0076     1.153980e+10  6.369800e+09   
15     5.727000e+09          0.0214     3.523600e+09  2.203400e+09   
16     1.972400e+10          0.0083     1.304100e+10  6.683000e+09   
17     8.268000e+09          0.0268     5.297000e+09  2.971000e+09   
...             ...             ...              ...           ...   
22070  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22073  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22075  5.488438e+07          0.2210     3.659379e+07  1.829059e+07   
22076  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22077  5.301900e+07          0.0243     0.000000e+00  5.301900e+07   

       R&D Expenses  SG&A Expense  Operating Expenses  Operating Income  \
2      1.083303e+08  3.441414e+08        7.939267e+08      1.345959e+08   
5      0.000000e+00  3.474300e+09        3.412400e+09      2.957400e+09   
15     0.000000e+00  1.480500e+09        1.598700e+09      6.047000e+08   
16     0.000000e+00  3.709000e+09        4.162000e+09      2.521000e+09   
17     1.220000e+08  1.505000e+09        1.704000e+09      1.267000e+09   
...             ...           ...                 ...               ...   
22070  1.572500e+07  5.269000e+06        2.099400e+07     -2.099400e+07   
22073  0.000000e+00  3.755251e+06        3.755251e+06     -3.755251e+06   
22075  1.652633e+06  7.020320e+06        8.672953e+06      9.617636e+06   
22076  1.031715e+07  4.521349e+06        1.664863e+07     -1.664863e+07   
22077  5.668400e+07  2.945700e+07        8.614600e+07     -3.312700e+07   

       Interest Expense  Earnings before Tax  ...  Consumer Cyclical  \
2          1.214869e+07         1.753823e+08  ...                  0   
5          3.024000e+08         2.707700e+09  ...                  0   
15         6.040000e+07         4.669000e+08  ...                  0   
16         2.840000e+08         2.382000e+09  ...                  0   
17         1.220000e+08         1.240000e+09  ...                  0   
...                 ...                  ...  ...                ...   
22070      0.000000e+00        -2.113800e+07  ...                  0   
22073      1.105849e+07        -1.482451e+07  ...                  0   
22075      1.239170e+06         8.416324e+06  ...                  0   
22076      0.000000e+00        -1.664769e+07  ...                  0   
22077      1.660000e+05        -3.438500e+07  ...                  0   

       Consumer Defensive  Energy  Financial Services  Healthcare  \
2                       1       0                   0           0   
5                       1       0                   0           0   
15                      1       0                   0           0   
16                      1       0                   0           0   
17                      1       0                   0           0   
...                   ...     ...                 ...         ...   
22070                   0       0                   0           1   
22073                   0       0                   0           0   
22075                   0       0                   0           0   
22076                   0       0                   0           0   
22077                   0       0                   0           1   

       Industrials  Real Estate  Technology  Utilities  SignalFac  
2                0            0           0          0          0  
5                0            0           0          0          2  
15               0            0           0          0          2  
16               0            0           0          0          2  
17               0            0           0          0          2  
...            ...          ...         ...        ...        ...  
22070            0            0           0          0          2  
22073            0            1 

In [8]:
X = df.drop('SignalFac',axis=1)
y = df['SignalFac']

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [12]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

# Create LDA object and run classifier
lda = LDA(solver='lsqr')
lda = lda.fit(X_train, y_train)
lda

# Relabel variables as discussed
X_test = X_train
y_test = y_train

# Predict labels
y_pred = lda.predict(X_test)

# Sklearn's confusion matrix
print(metrics.confusion_matrix(y_test, y_pred))


[[4083   21  207]
 [ 443   22   55]
 [2874   20  380]]


In [20]:
print('default-rate: {0: .4f}'.format(np.sum(y_train)/len(y_train)))
print('score:        {0: .4f}'.format(lda.score(X_train, y_train)))
print('error-rate:   {0: .4f}'.format(1-lda.score(X_train, y_train)))

default-rate:  0.8721
score:         0.5534
error-rate:    0.4466


## Lösen der Class Imbalance mit Upscaling

In [ ]:
#Hold werden upgesampled
#Sell werden downgesampled

In [30]:
print('Sell hat', X[y==0].shape[0], 'Werte')
print('Hold hat', X[y==1].shape[0], 'Werte')
print('Buy hat', X[y==2].shape[0], 'Werte')

Sell hat 6153 Werte
Hold hat 745 Werte
Buy hat 4681 Werte


In [52]:
from sklearn.utils import resample

X_upsampled, y_upsampled = resample(X[y==1], y[y==1],
                                    replace=True,
                                    n_samples=X[y==2].shape[0],
                                    random_state=1)

In [53]:
print(y_upsampled)

1082     1
6044     1
1980     1
20648    1
18402    1
        ..
16044    1
4925     1
20131    1
11114    1
7955     1
Name: SignalFac, Length: 4681, dtype: int64


In [32]:
print('Sell hat', X[y==0].shape[0], 'Werte')
print('Hold hat', X[y==1].shape[0], 'Werte')
print('Buy hat', X[y==2].shape[0], 'Werte')

Sell hat 6153 Werte
Hold hat 745 Werte
Buy hat 4681 Werte


In [45]:
# Downsampling
X_dnsampled, y_dnsampled = resample(X[y==0], y[y==0],
                                    replace=False,
                                    n_samples=X[y==2].shape[0],
                                    random_state=1)

In [49]:
print(y_dnsampled)

19074    0
8756     0
20915    0
1697     0
641      0
        ..
15394    0
17671    0
19508    0
1414     0
13597    0
Name: SignalFac, Length: 4681, dtype: int64
