In [130]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
plt.rcParams['font.size'] = 14
plt.style.use('seaborn-whitegrid')

In [131]:
df = pd.read_csv('cleaned_data/Cleaned Data.csv',index_col=[0])

In [132]:
df

Revenue  Revenue Growth  Cost of Revenue  Gross Profit  \
2      3.734148e+09          1.1737     2.805625e+09  9.285226e+08   
5      1.790960e+10          0.0076     1.153980e+10  6.369800e+09   
15     5.727000e+09          0.0214     3.523600e+09  2.203400e+09   
16     1.972400e+10          0.0083     1.304100e+10  6.683000e+09   
17     8.268000e+09          0.0268     5.297000e+09  2.971000e+09   
...             ...             ...              ...           ...   
22070  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22073  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22075  5.488438e+07          0.2210     3.659379e+07  1.829059e+07   
22076  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22077  5.301900e+07          0.0243     0.000000e+00  5.301900e+07   

       R&D Expenses  SG&A Expense  Operating Expenses  Operating Income  \
2      1.083303e+08  3.441414e+08        7.939267e+08      1.345959e+08   
5      0.000000e+00  3.474300e+09        3.412400e+09      2.957400e+09   
15     0.000000e+00  1.480500e+09        1.598700e+09      6.047000e+08   
16     0.000000e+00  3.709000e+09        4.162000e+09      2.521000e+09   
17     1.220000e+08  1.505000e+09        1.704000e+09      1.267000e+09   
...             ...           ...                 ...               ...   
22070  1.572500e+07  5.269000e+06        2.099400e+07     -2.099400e+07   
22073  0.000000e+00  3.755251e+06        3.755251e+06     -3.755251e+06   
22075  1.652633e+06  7.020320e+06        8.672953e+06      9.617636e+06   
22076  1.031715e+07  4.521349e+06        1.664863e+07     -1.664863e+07   
22077  5.668400e+07  2.945700e+07        8.614600e+07     -3.312700e+07   

       Interest Expense  Earnings before Tax  ...  Consumer Cyclical  \
2          1.214869e+07         1.753823e+08  ...                  0   
5          3.024000e+08         2.707700e+09  ...                  0   
15         6.040000e+07         4.669000e+08  ...                  0   
16         2.840000e+08         2.382000e+09  ...                  0   
17         1.220000e+08         1.240000e+09  ...                  0   
...                 ...                  ...  ...                ...   
22070      0.000000e+00        -2.113800e+07  ...                  0   
22073      1.105849e+07        -1.482451e+07  ...                  0   
22075      1.239170e+06         8.416324e+06  ...                  0   
22076      0.000000e+00        -1.664769e+07  ...                  0   
22077      1.660000e+05        -3.438500e+07  ...                  0   

       Consumer Defensive  Energy  Financial Services  Healthcare  \
2                       1       0                   0           0   
5                       1       0                   0           0   
15                      1       0                   0           0   
16                      1       0                   0           0   
17                      1       0                   0           0   
...                   ...     ...                 ...         ...   
22070                   0       0                   0           1   
22073                   0       0                   0           0   
22075                   0       0                   0           0   
22076                   0       0                   0           0   
22077                   0       0                   0           1   

       Industrials  Real Estate  Technology  Utilities  Signal  
2                0            0           0          0    Sell  
5                0            0           0          0     Buy  
15               0            0           0          0     Buy  
16               0            0           0          0     Buy  
17               0            0           0          0     Buy  
...            ...          ...         ...        ...     ...  
22070            0            0           0          0     Buy  
22073            0            1           0          0  

In [134]:
df['Signal'].value_counts()

Sell    6153
Buy     4681
Hold     745
Name: Signal, dtype: int64

In [121]:
SignalFac = []

for string in df['Signal']:
    if string == 'Sell':
        SignalFac.append(0)
    elif string == 'Hold':
        SignalFac.append(1)    
    else:
        SignalFac.append(2)

In [124]:
df['SignalFac'] = SignalFac
df.drop('Signal', axis=1, inplace=True)

In [96]:
df

Revenue  Revenue Growth  Cost of Revenue  Gross Profit  \
2      3.734148e+09          1.1737     2.805625e+09  9.285226e+08   
5      1.790960e+10          0.0076     1.153980e+10  6.369800e+09   
15     5.727000e+09          0.0214     3.523600e+09  2.203400e+09   
16     1.972400e+10          0.0083     1.304100e+10  6.683000e+09   
17     8.268000e+09          0.0268     5.297000e+09  2.971000e+09   
...             ...             ...              ...           ...   
22070  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22073  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22075  5.488438e+07          0.2210     3.659379e+07  1.829059e+07   
22076  0.000000e+00          0.0000     0.000000e+00  0.000000e+00   
22077  5.301900e+07          0.0243     0.000000e+00  5.301900e+07   

       R&D Expenses  SG&A Expense  Operating Expenses  Operating Income  \
2      1.083303e+08  3.441414e+08        7.939267e+08      1.345959e+08   
5      0.000000e+00  3.474300e+09        3.412400e+09      2.957400e+09   
15     0.000000e+00  1.480500e+09        1.598700e+09      6.047000e+08   
16     0.000000e+00  3.709000e+09        4.162000e+09      2.521000e+09   
17     1.220000e+08  1.505000e+09        1.704000e+09      1.267000e+09   
...             ...           ...                 ...               ...   
22070  1.572500e+07  5.269000e+06        2.099400e+07     -2.099400e+07   
22073  0.000000e+00  3.755251e+06        3.755251e+06     -3.755251e+06   
22075  1.652633e+06  7.020320e+06        8.672953e+06      9.617636e+06   
22076  1.031715e+07  4.521349e+06        1.664863e+07     -1.664863e+07   
22077  5.668400e+07  2.945700e+07        8.614600e+07     -3.312700e+07   

       Interest Expense  Earnings before Tax  ...  Consumer Cyclical  \
2          1.214869e+07         1.753823e+08  ...                  0   
5          3.024000e+08         2.707700e+09  ...                  0   
15         6.040000e+07         4.669000e+08  ...                  0   
16         2.840000e+08         2.382000e+09  ...                  0   
17         1.220000e+08         1.240000e+09  ...                  0   
...                 ...                  ...  ...                ...   
22070      0.000000e+00        -2.113800e+07  ...                  0   
22073      1.105849e+07        -1.482451e+07  ...                  0   
22075      1.239170e+06         8.416324e+06  ...                  0   
22076      0.000000e+00        -1.664769e+07  ...                  0   
22077      1.660000e+05        -3.438500e+07  ...                  0   

       Consumer Defensive  Energy  Financial Services  Healthcare  \
2                       1       0                   0           0   
5                       1       0                   0           0   
15                      1       0                   0           0   
16                      1       0                   0           0   
17                      1       0                   0           0   
...                   ...     ...                 ...         ...   
22070                   0       0                   0           1   
22073                   0       0                   0           0   
22075                   0       0                   0           0   
22076                   0       0                   0           0   
22077                   0       0                   0           1   

       Industrials  Real Estate  Technology  Utilities  SignalFac  
2                0            0           0          0          0  
5                0            0           0          0          2  
15               0            0           0          0          2  
16               0            0           0          0          2  
17               0            0           0          0          2  
...            ...          ...         ...        ...        ...  
22070            0            0           0          0          2  
22073            0            1 

In [97]:
X = df.drop('SignalFac',axis=1)
y = df['SignalFac']

In [98]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [99]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [100]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(solver='lsqr')
lda = lda.fit(X_train, y_train)
lda

LinearDiscriminantAnalysis(solver='lsqr')

In [101]:
print('default-rate: {0: .4f}'.format(np.sum(y_train)/len(y_train)))
print('score:        {0: .4f}'.format(lda.score(X_train, y_train)))
print('error-rate:   {0: .4f}'.format(1-lda.score(X_train, y_train)))

default-rate:  0.8721
score:         0.5777
error-rate:    0.4223


In [102]:
# Relabel variables as discussed
X_test = X_train
y_test = y_train

# Predict labels
y_pred = lda.predict(X_test)

# Sklearn's confusion matrix
print(metrics.confusion_matrix(y_test, y_pred))

[[3534   27  750]
 [ 324   28  168]
 [2131   23 1120]]


In [108]:
# Confusion matrix & clf-report for cut-off 
# value Pr(default=yes | X = x) > 0.20
print(metrics.confusion_matrix(y_test, y_pred020))
print(metrics.classification_report(y_test, y_pred020))

[[4208  103    0]
 [ 459   61    0]
 [3173  101    0]]
              precision    recall  f1-score   support

           0       0.54      0.98      0.69      4311
           1       0.23      0.12      0.16       520
           2       0.00      0.00      0.00      3274

    accuracy                           0.53      8105
   macro avg       0.26      0.36      0.28      8105
weighted avg       0.30      0.53      0.38      8105



C:\Users\Christian Rauhut\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
